# Generated by Django 3.2.5 on 2022-04-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('idDenominacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='Denominacion')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True, verbose_name='Pais')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Uva',
            fields=[
                ('idUva', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('idVino', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('precio', models.FloatField()),
                ('denominacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.denominacion')),
                ('uvas', models.ManyToManyField(to='main.Uva')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='denominacion',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pais'),
        ),
    ]
