# Generated by Django 5.1.2 on 2025-01-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_equipo_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='equipo',
        ),
    ]
